name: Experiments

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create Build Number
        run: echo "BUILDNUMBER::$(date +'%YYYY-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Use Build Number
        run: echo $BUILDNUMBER
