name: Experiments

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create Build Number
        id: buildnumber
        run: echo "::set-output name=buildnumber::$(date +'%Y-%m-%d')"
      - name: Use Build Number
        run: echo ${{ steps.buildnumber.outputs.buildnumber }}
